# Starting image
FROM alpine:3.17
LABEL maintainer "xamayuel@student.42urduliz.com"

RUN		apk add --no-cache --quiet --update php8 

RUN apk update && apk add --no-cache --quiet --update curl bash vim \
	mariadb-client  php-phar php-json php-curl php-fpm php-mysqli php-iconv




